<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9c31b709-e168-44b4-81e9-9785b8f0f925</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.15.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mango.MessageBus\Mango.MessageBus.csproj" />
  </ItemGroup>

</Project>
